/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 95a974fcaf716dc305d80af8a9689a6b)
interface __BaseEnv_Env {
	SESSIONS: DurableObjectNamespace<import("./src/worker").DemoSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "DemoSession";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
